--CREATE TABLES

DROP TABLE IF EXISTS `region`;

CREATE TABLE region (
id int PRIMARY KEY AUTO_INCREMENT,
nombre varchar(255),
codigo varchar(4),
capital varchar(155)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `candidato`;

CREATE TABLE candidato (
id int PRIMARY KEY AUTO_INCREMENT,
nombre varchar(255),
apellido varchar(255),
email varchar(255)

)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `comuna`;

CREATE TABLE comuna (
id int PRIMARY KEY AUTO_INCREMENT,
nombre varchar(255),
id_region int,

FOREIGN KEY (id_region) REFERENCES region(id)

)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `votacion`;

CREATE TABLE votacion (
id int PRIMARY KEY AUTO_INCREMENT,
nombre_apellido varchar(100),
alias varchar(255),
rut varchar(15),
email varchar(255),
id_region int,
id_comuna int,
id_candidato int,
difusion varchar(255),

UNIQUE (rut),
FOREIGN KEY (id_region) REFERENCES region(id),
FOREIGN KEY (id_comuna) REFERENCES comuna(id)
FOREIGN KEY (id_candidato) REFERENCES candidato(id)

)ENGINE=InnoDB DEFAULT CHARSET=utf8;


--INSERTS

INSERT INTO `region` (`nombre`,`codigo`,`capital`)
VALUES
('Arica y Parinacota','AP','Arica'),
('Tarapacá','TA','Iquique'),
('Antofagasta','AN','Antofagasta'),
('Atacama','AT','Copiapó'),
('Coquimbo','CO','La Serena'),
('Valparaiso','VA','valparaíso'),
('Metropolitana de Santiago','RM','Santiago'),
('Libertador General Bernardo O\Higgins','OH','Rancagua'),
('Maule','MA','Talca'),
('Ñuble','NB','Chillán'),
('Biobío','BI','Concepción'),
('La Araucanía','IAR','Temuco'),
('Los Ríos','LR','Valdivia'),
('Los Lagos','LL','Puerto Montt'),
('Aysén del General Carlos Ibáñez del Campo','AI','Coyhaique'),
('Magallanes y de la Antártica Chilena','MG','Punta Arenas');

INSERT INTO `comuna` (`nombre`,`id_region`)
VALUES
('Arica',1),
('Camarones',1),
('GeneralLagos',1),
('Putre',1),
('AltoHospicio',2),
('Iquique',2),
('Camiña',2),
('Colchane',2),
('Huara',2),
('Pica',2),
('PozoAlmonte',2),
('Tocopilla',3),
('MaríaElena',3),
('Calama',3),
('Ollague',3),
('SanPedrodeAtacama',3),
('Antofagasta',3),
('Mejillones',3),
('SierraGorda',3),
('Taltal',3),
('Chañaral',4),
('DiegodeAlmagro',4),
('Copiapó',4),
('Caldera',4),
('TierraAmarilla',4),
('Vallenar',4),
('AltodelCarmen',4),
('Freirina',4),
('Huasco',4),
('LaSerena',5),
('Coquimbo',5),
('Andacollo',5),
('LaHiguera',5),
('Paihuano',5),
('Vicuña',5),
('Ovalle',5),
('Combarbalá',5),
('MontePatria',5),
('Punitaqui',5),
('RíoHurtado',5),
('Illapel',5),
('Canela',5),
('LosVilos',5),
('Salamanca',5),
('LaLigua',6),
('Cabildo',6),
('Zapallar',6),
('Papudo',6),
('Petorca',6),
('LosAndes',6),
('SanEsteban',6),
('CalleLarga',6),
('Rinconada',6),
('SanFelipe',6),
('Llaillay',6),
('Putaendo',6),
('SantaMaría',6),
('Catemu',6),
('Panquehue',6),
('Quillota',6),
('LaCruz',6),
('LaCalera',6),
('Nogales',6),
('Hijuelas',6),
('Valparaíso',6),
('ViñadelMar',6),
('Concón',6),
('Quintero',6),
('Puchuncaví',6),
('Casablanca',6),
('JuanFernández',6),
('SanAntonio',6),
('Cartagena',6),
('ElTabo',6),
('ElQuisco',6),
('Algarrobo',6),
('SantoDomingo',6),
('IsladePascua',6),
('Quilpué',6),
('Limache',6),
('Olmué',6),
('VillaAlemana',6),
('Colina',7),
('Lampa',7),
('Tiltil',7),
('Santiago',7),
('Vitacura',7),
('SanRamón',7),
('SanMiguel',7),
('SanJoaquín',7),
('Renca',7),
('Recoleta',7),
('QuintaNormal',7),
('Quilicura',7),
('Pudahuel',7),
('Providencia',7),
('Peñalolén',7),
('PedroAguirreCerda',7),
('Ñuñoa',7),
('Maipú',7),
('Macul',7),
('LoPrado',7),
('LoEspejo',7),
('LoBarnechea',7),
('LasCondes',7),
('LaReina',7),
('LaPintana',7),
('LaGranja',7),
('LaFlorida',7),
('LaCisterna',7),
('Independencia',7),
('Huechuraba',7),
('EstaciónCentral',7),
('ElBosque',7),
('Conchalí',7),
('CerroNavia',7),
('Cerrillos',7),
('PuenteAlto',7),
('SanJosédeMaipo',7),
('Pirque',7),
('SanBernardo',7),
('Buin',7),
('Paine',7),
('CaleradeTango',7),
('Melipilla',7),
('Alhué',7),
('Curacaví',7),
('MaríaPinto',7),
('SanPedro',7),
('IsladeMaipo',7),
('ElMonte',7),
('PadreHurtado',7),
('Peñaflor',7),
('Talagante',7),
('Codegua',8),
('Coínco',8),
('Coltauco',8),
('Doñihue',8),
('Graneros',8),
('LasCabras',8),
('Machalí',8),
('Malloa',8),
('Mostazal',8),
('Olivar',8),
('Peumo',8),
('Pichidegua',8),
('QuintadeTilcoco',8),
('Rancagua',8),
('Rengo',8),
('Requínoa',8),
('SanVicentedeTaguaTagua',8),
('Chépica',8),
('Chimbarongo',8),
('Lolol',8),
('Nancagua',8),
('Palmilla',8),
('Peralillo',8),
('Placilla',8),
('Pumanque',8),
('SanFernando',8),
('SantaCruz',8),
('LaEstrella',8),
('Litueche',8),
('Marchigüe',8),
('Navidad',8),
('Paredones',8),
('Pichilemu',8),
('Curicó',9),
('Hualañé',9),
('Licantén',9),
('Molina',9),
('Rauco',9),
('Romeral',9),
('SagradaFamilia',9),
('Teno',9),
('Vichuquén',9),
('Talca',9),
('SanClemente',9),
('Pelarco',9),
('Pencahue',9),
('Maule',9),
('SanRafael',9),
('Curepto',9),
('Constitución',9),
('Empedrado',9),
('RíoClaro',9),
('Linares',9),
('SanJavier',9),
('Parral',9),
('VillaAlegre',9),
('Longaví',9),
('Colbún',9),
('Retiro',9),
('YerbasBuenas',9),
('Cauquenes',10),
('Chanco',10),
('Pelluhue',10),
('Bulnes',10),
('Chillán',10),
('ChillánViejo',10),
('ElCarmen',10),
('Pemuco',10),
('Pinto',10),
('Quillón',10),
('SanIgnacio',10),
('Yungay',10),
('Cobquecura',10),
('Coelemu',10),
('Ninhue',10),
('Portezuelo',10),
('Quirihue',10),
('Ránquil',10),
('Treguaco',10),
('SanCarlos',10),
('Coihueco',10),
('SanNicolás',10),
('Ñiquén',10),
('SanFabián',10),
('AltoBiobío',11),
('Antuco',11),
('Cabrero',11),
('Laja',11),
('LosÁngeles',11),
('Mulchén',11),
('Nacimiento',11),
('Negrete',11),
('Quilaco',11),
('Quilleco',11),
('SanRosendo',11),
('SantaBárbara',11),
('Tucapel',11),
('Yumbel',11),
('Concepción',11),
('Coronel',11),
('Chiguayante',11),
('Florida',11),
('Hualpén',11),
('Hualqui',11),
('Lota',11),
('Penco',11),
('SanPedrodeLaPaz',11),
('SantaJuana',11),
('Talcahuano',11),
('Tomé',11),
('Arauco',11),
('Cañete',11),
('Contulmo',11),
('Curanilahue',11),
('Lebu',11),
('LosÁlamos',11),
('Tirúa',11),
('Angol',12),
('Collipulli',12),
('Curacautín',12),
('Ercilla',12),
('Lonquimay',12),
('LosSauces',12),
('Lumaco',12),
('Purén',12),
('Renaico',12),
('Traiguén',12),
('Victoria',12),
('Temuco',12),
('Carahue',12),
('Cholchol',12),
('Cunco',12),
('Curarrehue',12),
('Freire',12),
('Galvarino',12),
('Gorbea',12),
('Lautaro',12),
('Loncoche',12),
('Melipeuco',12),
('NuevaImperial',12),
('PadreLasCasas',12),
('Perquenco',12),
('Pitrufquén',12),
('Pucón',12),
('Saavedra',12),
('TeodoroSchmidt',12),
('Toltén',12),
('Vilcún',12),
('Villarrica',12),
('Valdivia',13),
('Corral',13),
('Lanco',13),
('LosLagos',13),
('Máfil',13),
('Mariquina',13),
('Paillaco',13),
('Panguipulli',13),
('LaUnión',13),
('Futrono',13),
('LagoRanco',13),
('RíoBueno',13),
('Osorno',14),
('PuertoOctay',14),
('Purranque',14),
('Puyehue',14),
('RíoNegro',14),
('SanJuandelaCosta',14),
('SanPablo',14),
('Calbuco',14),
('Cochamó',14),
('Fresia',14),
('Frutillar',14),
('Llanquihue',14),
('LosMuermos',14),
('Maullín',14),
('PuertoMontt',14),
('PuertoVaras',14),
('Ancud',14),
('Castro',14),
('Chonchi',14),
('CuracodeVélez',14),
('Dalcahue',14),
('Puqueldón',14),
('Queilén',14),
('Quellón',14),
('Quemchi',14),
('Quinchao',14),
('Chaitén',14),
('Futaleufú',14),
('Hualaihué',14),
('Palena',14),
('LagoVerde',15),
('Coihaique',15),
('Aysén',15),
('Cisnes',15),
('Guaitecas',15),
('RíoIbáñez',15),
('ChileChico',15),
('Cochrane',15),
('O\Higgins',15),
('Tortel',15),
('Natales',16),
('TorresdelPaine',16),
('LagunaBlanca',16),
('PuntaArenas',16),
('RíoVerde',16),
('SanGregorio',16),
('Porvenir',16),
('Primavera',16),
('Timaukel',16),
('CabodeHornos',16),
('Antártica',16);



--CANDIDATOS

INSERT INTO `candidato` (`nombre`,`apellido`, email)
VALUES
('Juan','Perez','juan@gmail.com'),
('Leo','Diaz','juan@gmail.com'),
('Diego','Brito','juan@gmail.com'),
('Wilson','Saez','juan@gmail.com'),
('Andres','Vasquez','juan@gmail.com');